/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsICookie.idl"

[scriptable, uuid(53c53451-3b93-440c-b27b-9759ccb29da6)]
interface nsIFelt : nsISupports {
  [must_use]
  ACString oneShotIpcServer();

  [must_use]
  ACString binPath();

  [must_use]
  boolean makeBackgroundProcess();

  [must_use]
  boolean isFeltUI();

  [must_use]
  boolean isFeltBrowser();

  [must_use]
  void ipcChannel(in ACString profileKey);

  [must_use]
  void sendBoolPreference(in ACString name, in boolean value);

  [must_use]
  void sendStringPreference(in ACString name, in ACString value);

  [must_use]
  void sendIntPreference(in ACString name, in int32_t value);

  [must_use]
  void sendCookies(in Array<nsICookie> cookies);

  [must_use]
  void sendReady();

  [must_use]
  void sendRestartForced();
};
