# Default partner distribution configuration file
# Must be replaced as part of a repack for Enterprise builds

[Global]
id=enterprise-local
version=1.0
about=Mozilla Firefox Enterprise Local Build

[Preferences]
enterprise.console.address=https://fx-ent-console.zomilla.org
