/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(b0ca30e9-2cce-4f85-8a0a-07031e5244c5)]
interface nsIImeiProvider : nsISupports {
  [implicit_jscontext]
  readonly attribute Promise imei;
};

%{C++
#define NS_IMEI_PROVIDER_CONTRACTID "@mozilla.org/imei/provider;1"
%}
